{% set name = "biopython" %}
{% set version = "1.72" %}
{% set sha256 = "ab6b492443adb90c66267b3d24d602ae69a93c68f4b9f135ba01cb06d36ce5a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - Bio
    - Bio.Affy
    - Bio.Align
    - Bio.Align.Applications
    - Bio.AlignIO
    - Bio.Alphabet
    - Bio.Application
    - Bio.Blast
    - Bio.CAPS
    - Bio.Cluster
    - Bio.Compass
    - Bio.Crystal
    - Bio.Data
    - Bio.Emboss
    - Bio.Entrez
    - Bio.ExPASy
    - Bio.FSSP
    - Bio.GA
    - Bio.GA.Crossover
    - Bio.GA.Mutation
    - Bio.GA.Repair
    - Bio.GA.Selection
    - Bio.GenBank
    - Bio.Geo
    #Requires soft dependency reportlab
    #- Bio.Graphics
    #- Bio.Graphics.GenomeDiagram
    - Bio.HMM
    - Bio.KDTree
    - Bio.KEGG
    - Bio.KEGG.Compound
    - Bio.KEGG.Enzyme
    - Bio.KEGG.KGML
    - Bio.KEGG.Map
    - Bio.Medline
    - Bio.NMR
    - Bio.NeuralNetwork
    - Bio.NeuralNetwork.BackPropagation
    - Bio.NeuralNetwork.Gene
    - Bio.Nexus
    - Bio.PDB
    - Bio.PDB.QCPSuperimposer
    #Requires soft dependency mmtf-python
    #- Bio.PDB.mmtf
    - Bio.Pathway
    - Bio.Pathway.Rep
    - Bio.Phylo
    - Bio.Phylo.Applications
    - Bio.Phylo.PAML
    - Bio.PopGen
    - Bio.PopGen.GenePop
    - Bio.Restriction
    - Bio.SCOP
    - Bio.SVDSuperimposer
    - Bio.SearchIO
    - Bio.SearchIO.BlastIO
    - Bio.SearchIO.ExonerateIO
    - Bio.SearchIO.HmmerIO
    - Bio.SearchIO._model
    - Bio.SeqIO
    - Bio.SeqUtils
    - Bio.Sequencing
    - Bio.Sequencing.Applications
    - Bio.Statistics
    - Bio.SubsMat
    - Bio.SwissProt
    - Bio.TogoWS
    - Bio.UniGene
    - Bio.UniProt
    - Bio.Wise
    - Bio._py3k
    - Bio.codonalign
    - Bio.cpairwise2
    - Bio.motifs
    - Bio.motifs.applications
    - Bio.motifs.jaspar
    - Bio.phenotype
    - Bio.trie
    - BioSQL
    
about:
  home: http://biopython.org
  license: Biopython License Agreement
  license_file: LICENSE.rst
  summary: 'Collection of freely available tools for computational molecular biology'
  description: |
    Biopython is a collection of freely available Python tools for
    computational molecular biology
  doc_url: http://biopython.org
  dev_url: https://github.com/biopython/biopython

extra:
  recipe-maintainers:
    - souravsingh
    - peterjc
