appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: WdOQKCnDNl0XV1L+jBioLpupzRKya1pADRRXiPN+et2v4PdpuZCzI85ef87+5GRJyJJ5E+g0XgNjOTJfFmGVJdtF3jXXjamnXHN0pmtXpqp2QOnAy4SOSEKEA8rK11KqxBrVdjLSt5S5Avn03NRQT4Oqh8mhvgnXjb8undw5P8s9AUnkotD9gJWX+TVLBxo2d70DLqyBkDMHH/yYiDlBnzFSpBK/YpnqWlv3LC4tER6vdvxNrmATOoJOt00GZMpdPvmnXF9o1KaTTRJqjoaV9c5XDkgYQ5tNJydOT8Ffk86wHO6Sf2oPX9UOWb9IcBb6kS4aYy5oU+QF6moN5+UhWyuPd3p8PNVASg0riJn9vfLjyzbyHOA0WGYwCuIa3n5jBGj39SrRuMOn9vHVPxcM14dRu6cQ0bUlT5J+Xdg1wcRIaFk1FgUAO9KLJ2MUUcgJf/F8aE2Nq5XDtRe061CSSB/wurGIRJnyp5H/4cwk+ep0O2yjbT6uyZ+sDF31Et+k5MADUmLhK48Lc4pAJ7Uz/hy4+Tu5fW6ENyq6FqV+Jablnh4Om6G0B5iRnM0OSXEfhdavcLaBtXELeXDNqpqeCMf4FdcJ7yBO1P6WLHTAIBFNcbNrK32KR4dYSmtg7P+KRa81icKBOrBowO6vpZDjIlWblwhIev70vinM2HA5riM=}
provider:
  win: azure
conda_forge_output_validation: true
